### ISSUE TITLE
Class method exiting the program

### ISSUE THREAD

**Issue by vmartirosyan** [Rafayelyan/Automata-simulator#2]
Class methods, including constructors, are not allowed to exit programs, as there could be other work going on except the automata functionality in the program. It can also affect some resources, like files, database connections etc.

https://github.com/Rafayelyan/Automata-simulator/blob/e6724165e793e25b25ef30745ffc269c9b487192/automata.cpp#L30

**Comment by Rafayelyan** [comment]
done.
